version: '3.8'

networks:
  bridge_network:
    driver: bridge


services:
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    networks:
      - bridge_network
    volumes:
      - ..:/workspace:cached


  triton:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.triton
    networks:
      - bridge_network